site_name: RIBLab-Network-Wiki
theme:
    name: material
    langage: ja
    features:
    - navigation.footer
    copyright: © 2023 RIBLab</br>当ホームページの内容について，「私的使用のための複製」や「引用」など著作権法上認められた場合を除き，無断で複製・転用することはできません。
    palette:
        - scheme: default
          primary: green
          toggle:
              icon: material/toggle-switch-off-outline
              name: ダークモードに切り替えます。
        - scheme: slate
          primary: green
          toggle:
              icon: material/toggle-switch
              name: ライトモードに切り替えます。
markdown_extensions:
    # アラート修飾の設定
    - admonition
    # スーパーフェンス機能の設定
    - pymdownx.superfences
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
nav:
    - ホーム: /
    - RIBLabとは？: about/
    - 参加方法: join/
    - ルール: rules/
