site_name: RIBLab-Network-Wiki
theme:
    name: material
    langage: ja
    features:
    - navigation.footer
    font:
      text: Zen Maru Gothic
    logo: assets/81ed1af081d1e480dfe12d1065d4134a.png
    palette:
        - scheme: default
          primary: blue
          toggle:
              icon: material/toggle-switch-off-outline
              name: ダークモードに切り替えます。
        - scheme: slate
          primary: blue
          toggle:
              icon: material/toggle-switch
              name: ライトモードに切り替えます。
markdown_extensions:
    # アラート修飾の設定
    - admonition
    # スーパーフェンス機能の設定
    - pymdownx.superfences
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
nav:
    - ホーム: /
    - RIBLabとは？: about/
    - ルール: rules/
    - 参加方法: join/
